### ISSUE TITLE
Deal with black Color objects appearing as empty objects in JSON responses (was: Issue in get_conditional_format_rules)

### ISSUE THREAD

**Issue by rjamorim** [robin900/gspread-formatting#31] opened 2021-05-10 03:16 UTC
Hello Robin

I am experiencing an issue that is either a problem with parsing the results in get_conditional_format_rules, or I am misusing ConditionalFormatRule(). Let me explain:

I am adding three conditional format rules to a spreadsheet, like this:
>    rule1 = gf.ConditionalFormatRule(
>        ranges=[gf.GridRange(worksheet.id, 1, len(calendar.index), 1, len(calendar.columns))],
>        booleanRule=gf.BooleanRule(gf.BooleanCondition('NUMBER_EQ', ['1']), gf.CellFormat(textFormat=gf.TextFormat(foregroundColor=gf.Color.fromHex("#000000")))))

(the other two are pretty much the same, with slightly different BooleanCondition and color hex)

After the code is run for the first time, the rules are successfully written to my worksheet  - I check it at Format -> Conditional formatting

When I run it for the second time, the call to get_conditional_format_rules crashes with the following error:

>  File "/usr/local/lib/python3.9/site-packages/gspread_formatting/models.py", line 11, in from_props
>    return _props_to_component(_CLASSES, _underlower(cls.__name__), props)
>  File "/usr/local/lib/python3.9/site-packages/gspread_formatting/util.py", line 98, in _props_to_component
>    v = _props_to_component(class_registry, item_alias, v, True)
>  File "/usr/local/lib/python3.9/site-packages/gspread_formatting/util.py", line 101, in _props_to_component
>    return cls(**kwargs) if (kwargs or not none_if_empty) else None
> TypeError: __init__() missing 1 required positional argument: 'format'

To debug, I cleared formatting in the entire worksheet and tried creating a rule directly at GSheets and running my code. 

This time it completed successfully, and this is the outcome of printing the rule obtained by get_conditional_format_rules, plus the rules I had just appended():

> ranges=[<GridRange sheetId=0;startRowIndex=9;endRowIndex=10;startColumnIndex=2;endColumnIndex=3>];booleanRule=(condition=(type=NOT_BLANK;values=[]);format=(backgroundColor=(red=0.7176471;green=0.88235295;blue=0.8039216);textFormat=(bold=True);backgroundColorStyle=(rgbColor=(red=0.7176471;green=0.88235295;blue=0.8039216))))
> ranges=[<GridRange sheetId=0;startRowIndex=1;endRowIndex=50;startColumnIndex=1;endColumnIndex=365>];booleanRule=(condition=(type=NUMBER_EQ;values=[<ConditionValue userEnteredValue=1>]);format=(textFormat=(foregroundColor=(red=0.0;green=0.0;blue=0.0))))
> ranges=[<GridRange sheetId=0;startRowIndex=1;endRowIndex=50;startColumnIndex=1;endColumnIndex=365>];booleanRule=(condition=(type=NUMBER_EQ;values=[<ConditionValue userEnteredValue=0.5>]);format=(textFormat=(foregroundColor=(red=0.0;green=0.0;blue=1.0))))
> ranges=[<GridRange sheetId=0;startRowIndex=1;endRowIndex=51;startColumnIndex=1;endColumnIndex=366>];booleanRule=(condition=(type=NUMBER_EQ;values=[<ConditionValue userEnteredValue=0>]);format=(textFormat=(foregroundColor=(red=1.0;green=0.0;blue=0.0))))`

![image](https://user-images.githubusercontent.com/10819319/117602254-97e25c00-b126-11eb-8071-ef6241bdbfef.png)

Sure enough, it crashed when I tried running it again immediately afterward.

**My hunch** is that the rules I am creating are valid (Google accepts and applies them without issues) but the parser in get_conditional_format_rules is expecting something else there.

Thank you for your time

**Version and Environment**
*Version of package*: 0.3.7
*Python interpreter*: CPython 3.9
*OS*: macOS

**Comment by robin900** [comment] 2021-05-10 13:31
@rjamorim Thank you for the very thorough bug report. Although the test suite does already have a round-trip test for conditional format rules, I'm creating another test using your code samples above. Will update asap.

**Comment by robin900** [comment] 2021-05-10 13:43
I think I've found a clue: conditional format rules whose cellFormat contains only a textFormat that sets a color (either foreground or background) to `\#000000` results in JSON that is effectively empty when fetched from the API, e.g.:

```
u'format': {u'textFormat': {u'foregroundColor': {}, u'foregroundColorStyle': {u'rgbColor': {}}}}
```

And this is being interpreted by the parsing code as an "empty" object that is better represented as `None`, and thus omitted from the arguments passed to the object constructor.

Working on a fix; it may take until later today to release the fix in PyPI.

**Comment by rjamorim** [comment] 2021-05-10 14:05
Hello Robin

You are correct! I commented out the line that appends the rule which is setting the text to black (actually quite useless, if you think about it, as that is the default) and now I can run the code repeatedly without get_conditional_format_rules throwing an error.

I wonder if that is not a bug on Google's side as well, for returning the empty JSON.

Thank you for your quick reply!

**Comment by robin900** [comment] 2021-05-10 15:08
I have found the JSON in responses from the Sheets API to be frustratingly inconsistent. Even in cases where a color property _needs_ to be absent -- so that it does not specify black by accident -- the response JSON has an empty `{}` for the color property instead of omitting the property entirely. 

Example: `InterpolationPoint` has either a color _or_ a colorStyle property, but response JSON always includes an empty/black color property if colorStyle is specified. However, `ColorStyle` itself has either a themeColor enum property _or_ an rbgColor property of type `Color`; in response JSON, the colorStyle object always properly omits rgbColor if themeColor is specified. Grrrrrr!

I need to think for a few hours more on this. I have a hunch (or maybe just a hope) that the correct solution to this problem hinges on the interaction of `affectedFields` and default values of formatting properties. Perhaps once the meaning of default values is considered, the API's response JSON actually has some kind of consistency that can guide the code in this Python package. Update later today.

**Comment by rjamorim** [comment] 2021-05-10 17:31
I see... quite a mess!

Well, take your time, I commented out the append() code and I'm not in a hurry to enable it back. And thank you for your time!

**Comment by robin900** [comment] 2021-05-10 18:16
So I think I've come to understand the problem, and I'm putting my notes here:

1. Sheets API like other Google APIs has a discovery document -- a data model and list of endpoints -- that is based on JSON Schema and that is machine-readable. But the API discovery document doesn't include any use of `oneOf`, `allOf`, or `anyOf` in its data schema. 
2. There are certain API objects that have what they call "union fields" (`oneOf` in JSON Schema speak): there are two properties but exactly one of them must be specified, not both or neither. This is documented in the API reference documentation (as a weird little code comment) but _not_ in the JSON Schema discovery document. For example, `ColorStyle` has a union field of `themeColor` and `rgbColor`; this is documented in the reference documentation but _not_ in the discovery JSON.
3. Other objects have things that you would expect to be "union fields", but in fact they are not. `TextFormat` has the properties `foregroundColor` and `foregroundColorStyle`, but they are not a union field. Instead, if both foregroundColor and foregroundColorStyle are present, foregroundColorStyle "takes precedence" over foregroundColor.
4. When an object has a true "union field" indicated in the docs, the API response JSON will include exactly one of the properties in the union -- whichever one had a value specified. 
5. When an object has a "pseudo union field", the API response JSON will include both fields in every case.
6. The Sheets API seems to like to return empty objects in JSON response to indicate that the object has default values for all of its properties. I cannot yet find explanation in any documentation for this phenomenon.
6. Which brings us to the `Color` object. The Color object has four float properties (red, green, blue, alpha), and the (not well-documented) default values are 0.0, 0.0, 0.0, and 1.0 respectively. If you specify a Color object with `red=1.0` and store it via API somewhere and fetch it again, the object JSON will be `{'red': 1.0}`. If you specify a Color object with `red=0, green=0, blue=0` and store it and fetch it, the object JSON will be `{}` to indicate "all values are default", which means black with no alpha transparency. 
7. I cannot yet find another API object besides `Color` that has defined default values for all of its properties, but perhaps one exists. Since `Color` occurs so frequently in the data model of the API, we must account for the empty-means-all-default-values case for Color; but it would be great to implement a general solution so that if other objects in the schema are found to share this characteristic, it will be trivial to support in this package.
8. I must verify whether storing a Color object as `{}` is interpreted by the API as meaning a specified color black-no-transparency in all situations.

If I can confirm \#8 above, I think the smallest correct solution will be to introduce a "default values" aspect to the formatting object class framework in my package, and then specifying default values for all the stuff. This new aspect will be used by serialization/deserialization code so that reading `{}` for Color will result in a full object with red=0.0, blue=0.0, green=0.0, alpha=1.0; and writing the object to JSON will result in `{}`.

But this solution does not solve the "union field" problem, and I have to think more about that.

I do not guarantee that I can verify \#8 and write a solution today.  But soon.

**Comment by robin900** [comment] 2021-05-13 16:20
The solution is progressing nicely, but it's apparent that if it gets merged into a release, it will break backward compatbility in subtle ways. Any users of this package whose code depends on CellFormat objects remaining equivalent once stored and fetched will experience problems because the fetched objects will now contain default Color objects in properties that hadn't been set in the CellFormat being stored. It is unlikely that many package users have code like this, but I'll need to do a major version number increase to warn about the possible changes.

**Closed as completed** 2021-05-13 16:46 UTC
Labels: bug

**Comment by robin900** [comment] 2021-05-13 16:53
PyPI now has release 1.0.0 with the fix, @rjamorim .

**Comment by rjamorim** [comment] 2021-05-13 17:02
Awesome @robin900. Thank you very much for answering so quickly and for taking the time to study the issue and come up with the best solution.

I can confirm the bug is no longer happening in my code
