### ISSUE TITLE
AttributeError: 'list' object has no attribute 'to_props'

### ISSUE THREAD

**Issue by heskarioth** [robin900/gspread-formatting#41] opened 2022-02-04 18:15 UTC
**Describe the bug**

I am unable to save new rules to my worksheet.

**Version and Environment**
*Version of package*: 1.0.5
Jupyter Notebooks - Anaconda 
Python 3.8.3

**To Reproduce**

#intiate client 
client = gspread.authorize(creds)
worksheet=client.open_by_key(GOOGLE_SHEET_ID)
sheet =worksheet.worksheet('V')
#get all conditional formatting rules
rules = get_conditional_format_rules(sheet)
#save them
rule1 = rules[0]
rule2 = rules[1]
#clear existing ones
rules.clear()
#add new rule 
rules.append(rule2)
#save 
rules.save()

**Expected behavior**
Expected behaviour is to save the new conditional formatting ( I haven't made any changes to the rule1 object but intend to do so)
**Screenshots**

**Desktop (please complete the following information):**
Windows
 - Browser Chrome

**Additional context**
![image](https://user-images.githubusercontent.com/17654990/152581761-4829892d-18ee-49c5-b162-a8026c12fd0d.png)

**Comment by robin900** [comment] 2022-02-04 19:00
@heskarioth What is the actual behavior? Does save() complete without an exception, and there is no change to the rules in the sheet? Or is an exception raised?

**Comment by robin900** [comment] 2022-02-07 06:27
@heskarioth I can only reproduce your error if I `.append()` or set an item to be an actual list, e.g.
```
rules.append([])
# or
rules.insert(0, [])
```

Using the sample code you provided above, I cannot reproduce the error. My guess is that the code you are actually running differs from what is pasted above. Would you double-check your code and let me know?

**Comment by robin900** [comment] 2022-02-09 19:22
I've added type checking for the `ConditionalFormatRules` object, so that only items of type `ConditionalFormatRule` can be added to it. That is now in release 1.0.6 in PyPI. Closing this issue.

**Closed as completed by robin900** 2022-02-09 19:22 UTC
